require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrokenLinksController do

  # This should return the minimal set of attributes required to create a valid
  # BrokenLink. As you add validations to BrokenLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "url" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrokenLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all broken_links as @broken_links" do
      broken_link = BrokenLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:broken_links).should eq([broken_link])
    end
  end

  describe "GET show" do
    it "assigns the requested broken_link as @broken_link" do
      broken_link = BrokenLink.create! valid_attributes
      get :show, {:id => broken_link.to_param}, valid_session
      assigns(:broken_link).should eq(broken_link)
    end
  end

  describe "GET new" do
    it "assigns a new broken_link as @broken_link" do
      get :new, {}, valid_session
      assigns(:broken_link).should be_a_new(BrokenLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested broken_link as @broken_link" do
      broken_link = BrokenLink.create! valid_attributes
      get :edit, {:id => broken_link.to_param}, valid_session
      assigns(:broken_link).should eq(broken_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BrokenLink" do
        expect {
          post :create, {:broken_link => valid_attributes}, valid_session
        }.to change(BrokenLink, :count).by(1)
      end

      it "assigns a newly created broken_link as @broken_link" do
        post :create, {:broken_link => valid_attributes}, valid_session
        assigns(:broken_link).should be_a(BrokenLink)
        assigns(:broken_link).should be_persisted
      end

      it "redirects to the created broken_link" do
        post :create, {:broken_link => valid_attributes}, valid_session
        response.should redirect_to(BrokenLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved broken_link as @broken_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrokenLink.any_instance.stub(:save).and_return(false)
        post :create, {:broken_link => { "url" => "invalid value" }}, valid_session
        assigns(:broken_link).should be_a_new(BrokenLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrokenLink.any_instance.stub(:save).and_return(false)
        post :create, {:broken_link => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested broken_link" do
        broken_link = BrokenLink.create! valid_attributes
        # Assuming there are no other broken_links in the database, this
        # specifies that the BrokenLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BrokenLink.any_instance.should_receive(:update_attributes).with({ "url" => "MyText" })
        put :update, {:id => broken_link.to_param, :broken_link => { "url" => "MyText" }}, valid_session
      end

      it "assigns the requested broken_link as @broken_link" do
        broken_link = BrokenLink.create! valid_attributes
        put :update, {:id => broken_link.to_param, :broken_link => valid_attributes}, valid_session
        assigns(:broken_link).should eq(broken_link)
      end

      it "redirects to the broken_link" do
        broken_link = BrokenLink.create! valid_attributes
        put :update, {:id => broken_link.to_param, :broken_link => valid_attributes}, valid_session
        response.should redirect_to(broken_link)
      end
    end

    describe "with invalid params" do
      it "assigns the broken_link as @broken_link" do
        broken_link = BrokenLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrokenLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => broken_link.to_param, :broken_link => { "url" => "invalid value" }}, valid_session
        assigns(:broken_link).should eq(broken_link)
      end

      it "re-renders the 'edit' template" do
        broken_link = BrokenLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrokenLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => broken_link.to_param, :broken_link => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested broken_link" do
      broken_link = BrokenLink.create! valid_attributes
      expect {
        delete :destroy, {:id => broken_link.to_param}, valid_session
      }.to change(BrokenLink, :count).by(-1)
    end

    it "redirects to the broken_links list" do
      broken_link = BrokenLink.create! valid_attributes
      delete :destroy, {:id => broken_link.to_param}, valid_session
      response.should redirect_to(broken_links_url)
    end
  end

end
